//! Generates the zone-id/zone-path validation rules from the materialized
//! owner specs, so this crate can never disagree with nexus-vfs about what a
//! zone id or path is.
//!
//! The specs are materialized by `contracts/generate.mjs` from the revision
//! pinned in `contracts/zone-v1/pin.json`; the reserved-id VALUES live in the
//! compiled projections (the spec names them by constant, the projections
//! enumerate them), so both are read here.
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let projections = manifest_dir
        .join("..")
        .join("..")
        .join("contracts")
        .join("zone-v1")
        .join("projections.gen");
    println!("cargo:rerun-if-changed={}", projections.display());

    let id_spec: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(projections.join("zone-id-spec.json")).expect("zone-id spec"))
            .expect("parse zone-id spec");
    let path_spec: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(projections.join("zone-path-spec.json")).expect("zone-path spec"))
            .expect("parse zone-path spec");
    let tenant: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(projections.join("tenant-zone-id-create.schema.gen.json")).expect("tenant projection"),
    )
    .expect("parse tenant projection");
    let existing: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(projections.join("existing-zone-id-ref.schema.gen.json")).expect("existing projection"),
    )
    .expect("parse existing projection");
    let path_projection: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(projections.join("zone-path.schema.gen.json")).expect("zone-path projection"),
    )
    .expect("parse zone-path projection");

    // The spec names reserved path prefixes by constant (SYSTEM_PATH_PREFIX);
    // the compiled projection enumerates their values as negative lookaheads
    // of the form `(?!name(?:/|$))`. Extract them from the pattern so the
    // values still have exactly one owner.
    let mut reserved_path_prefixes: Vec<String> = Vec::new();
    {
        let pattern = path_projection["pattern"].as_str().expect("path pattern");
        let mut rest = pattern;
        while let Some(idx) = rest.find("(?!") {
            let after = &rest[idx + 3..];
            match after.find("(?:/|$))") {
                Some(end) => {
                    reserved_path_prefixes.push(after[..end].to_string());
                    rest = &after[end..];
                }
                None => break,
            }
        }
    }
    assert!(
        !reserved_path_prefixes.is_empty(),
        "no reserved path prefixes extracted from the projection pattern"
    );

    // Reserved values are enumerated inside the compiled projections:
    // tenant-create has them in `not.enum` (rejected), existing-ref in the
    // `anyOf` enum branch (accepted).
    let reserved_tenant: Vec<String> = tenant["allOf"][1]["not"]["enum"]
        .as_array()
        .expect("tenant reserved enum")
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let reserved_existing: Vec<String> = existing["anyOf"][1]["enum"]
        .as_array()
        .expect("existing reserved enum")
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();

    let id = &id_spec;
    let path = &path_spec;
    let out = format!(
        r#"// @generated by crates/sudo-contracts/build.rs from the materialized nexus-vfs specs — do not edit.
// Source: contracts/zone-v1/projections.gen/ (pinned revision in contracts/zone-v1/pin.json).

pub const ZONE_ID_MIN_LEN: usize = {id_min};
pub const ZONE_ID_MAX_LEN: usize = {id_max};
pub const ZONE_ID_CHARSET: &str = {id_charset};
pub const ZONE_ID_NO_LEADING: char = {lead};
pub const ZONE_ID_NO_TRAILING: char = {trail};
pub const RESERVED_TENANT: &[&str] = &[{reserved_tenant}];
pub const RESERVED_EXISTING: &[&str] = &[{reserved_existing}];

pub const ZONE_PATH_MAX_LEN: usize = {path_max};
pub const ZONE_PATH_MAX_DEPTH: usize = {depth};
pub const ZONE_PATH_COMPONENT_ALLOWED: &str = {comp_allowed};
pub const ZONE_PATH_FORBIDDEN_COMPONENTS: &[&str] = &[{comp_forbidden}];
pub const ZONE_PATH_RESERVED_PREFIXES: &[&str] = &[{path_reserved}];
"#,
        path_reserved = reserved_path_prefixes
            .iter()
            .map(|s| format!("{:?}", s))
            .collect::<Vec<_>>()
            .join(", "),
        id_min = id["length"]["min"],
        id_max = id["length"]["max"],
        id_charset = format!("{:?}", id["charset"]["allowed"].as_str().unwrap()),
        lead = format!("{:?}", id["edges"]["no_leading"].as_str().unwrap().chars().next().unwrap()),
        trail = format!("{:?}", id["edges"]["no_trailing"].as_str().unwrap().chars().next().unwrap()),
        reserved_tenant = reserved_tenant
            .iter()
            .map(|s| format!("{:?}", s))
            .collect::<Vec<_>>()
            .join(", "),
        reserved_existing = reserved_existing
            .iter()
            .map(|s| format!("{:?}", s))
            .collect::<Vec<_>>()
            .join(", "),
        path_max = path["length"]["max"],
        depth = path["depth"]["max"],
        comp_allowed = format!("{:?}", path["component"]["allowed"].as_str().unwrap()),
        comp_forbidden = path["component"]["forbidden"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| format!("{:?}", v.as_str().unwrap()))
            .collect::<Vec<_>>()
            .join(", "),
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("generated_rules.rs"), out).unwrap();
}
