// @generated by contracts/generate.mjs — do not edit.
// Nexus source revision: 759842551697efa2579a92f24b16f8ae43829e7b
// Nexus definition revision: 5139e2019d7f46d4dde3f73ee6cd21bb094a7dc1
// nexus-vfs primitive revision: 24f6730ec90fab8a035b2f5400ed313bda343fbe

import Ajv2020 from 'ajv/dist/2020.js'
import { getNodeValue, parseTree } from 'jsonc-parser'
import { readFileSync } from 'node:fs'

const readJson = (relativePath: string): Record<string, unknown> =>
  JSON.parse(readFileSync(new URL(relativePath, import.meta.url), 'utf8')) as Record<string, unknown>

const RESOURCE_SCHEMA = readJson('./schema.gen.json')
const ZONE_ID_SCHEMA = readJson('../../../zone-id/schema.gen.json')
const ZONE_PATH_SCHEMA = readJson('../../../zone-path/schema.gen.json')
const ZONE_PATH_META_SCHEMA = readJson('../../../zone-path/meta-schema.gen.json')

export const RESOURCE_REF_API_VERSION = "common.sudo.dev/v1" as const
export const RESOURCE_REF_KIND = "ResourceRef" as const
export const MAX_RESOURCE_REF_JSON_BYTES: number = Number(RESOURCE_SCHEMA['x-sudo-max-json-bytes'])
export const MAX_EXTENSION_DEPTH: number = Number(RESOURCE_SCHEMA['x-sudo-max-extension-depth'])
const SAFE_EXTENSION_VALUE = (
  RESOURCE_SCHEMA.$defs as Record<string, Record<string, unknown>>
).safe_extension_value_0
const MAX_EXTENSION_STRING_LENGTH = Number(SAFE_EXTENSION_VALUE.maxLength)
const MAX_EXTENSION_ITEMS = Number(SAFE_EXTENSION_VALUE.maxItems)
const MAX_EXTENSION_PROPERTIES = Number(SAFE_EXTENSION_VALUE.maxProperties)

const MIN_SAFE_JSON_INTEGER = Number.MIN_SAFE_INTEGER
const MAX_SAFE_JSON_INTEGER = Number.MAX_SAFE_INTEGER
const KNOWN_FIELDS = new Set(Object.keys(RESOURCE_SCHEMA.properties as object))
const SAFE_PROPERTY_SCHEMA = (
  RESOURCE_SCHEMA.$defs as Record<string, Record<string, unknown>>
).safe_property_name
const SAFE_PROPERTY_RULES = SAFE_PROPERTY_SCHEMA.allOf as Array<Record<string, unknown>>
const SAFE_PROPERTY_PATTERN_RULE = SAFE_PROPERTY_RULES.find((rule) => typeof rule.pattern === 'string')
const SECRET_PROPERTY_PATTERN_RULE = SAFE_PROPERTY_RULES.find(
  (rule) => typeof (rule.not as Record<string, unknown> | undefined)?.pattern === 'string',
)
if (!SAFE_PROPERTY_PATTERN_RULE || !SECRET_PROPERTY_PATTERN_RULE) {
  throw new Error('ResourceRef property-name policy is incomplete')
}
const SAFE_PROPERTY_PATTERN = new RegExp(String(SAFE_PROPERTY_PATTERN_RULE.pattern), 'u')
const SECRET_PROPERTY_PATTERN = new RegExp(
  String((SECRET_PROPERTY_PATTERN_RULE.not as Record<string, unknown>).pattern),
  'u',
)

export type JsonValue =
  | null
  | boolean
  | string
  | number
  | JsonValue[]
  | { [key: string]: JsonValue }

export interface ResourceRef {
  api_version: typeof RESOURCE_REF_API_VERSION
  kind: typeof RESOURCE_REF_KIND
  zone_id: string
  path: string
  version?: string
  digest?: string
  media_type?: string
  size_bytes?: string
  [key: string]: JsonValue | undefined
}

export interface ResourceRefValidationIssue {
  category: string
  path: string
  keyword: string
  message: string
}

export class ResourceRefValidationError extends Error {
  readonly issues: readonly ResourceRefValidationIssue[]

  constructor(issues: readonly ResourceRefValidationIssue[]) {
    super(
      'ResourceRef validation failed: ' +
        issues.map((issue) => (issue.path || '/') + ': ' + issue.category).join('; '),
    )
    this.name = 'ResourceRefValidationError'
    this.issues = issues
  }
}

const issue = (
  category: string,
  path: string,
  keyword: string,
  message: string,
): ResourceRefValidationIssue => ({ category, path, keyword, message })

function isUnicodeScalarString(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index)
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(index + 1)
      if (!(next >= 0xdc00 && next <= 0xdfff)) return false
      index += 1
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      return false
    }
  }
  return true
}

function exceedsUnicodeScalarLength(value: string, limit: number): boolean {
  let count = 0
  for (const _character of value) {
    count += 1
    if (count > limit) return true
  }
  return false
}

function validateZonePathRules(rules: Record<string, unknown>, value: string): boolean {
  if (rules.unicode_scalar_values_only === true && !isUnicodeScalarString(value)) return false
  if (rules.empty === 'reject' && value.length === 0) return false
  const separator = String(rules.separator)
  const root = String(rules.root)
  if (rules.absolute === true && !value.startsWith(separator)) return false
  if (value === root) return true
  if (rules.trailing_separator === 'root-only' && value.endsWith(separator)) return false
  if (rules.repeated_separators === 'reject' && value.includes(separator + separator)) return false
  const forbiddenCharacters = rules.forbidden_characters as string[]
  if ([...value].some((character) => forbiddenCharacters.includes(character))) return false
  const forbiddenSegments = rules.forbidden_exact_segments as string[]
  return !value.split(separator).slice(1).some((segment) => forbiddenSegments.includes(segment))
}

function addAnnotationKeywords(ajv: Ajv2020): void {
  const annotations = new Set<string>()
  const visit = (value: unknown): void => {
    if (Array.isArray(value)) {
      value.forEach(visit)
      return
    }
    if (!value || typeof value !== 'object') return
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith('x-sudo-')) annotations.add(key)
      visit(child)
    }
  }
  ;[RESOURCE_SCHEMA, ZONE_ID_SCHEMA, ZONE_PATH_SCHEMA, ZONE_PATH_META_SCHEMA].forEach(visit)
  for (const keyword of annotations) ajv.addKeyword({ keyword, valid: true })
}

function createStructuralValidator() {
  // The owner schema applies string types at the parent and patterns inside allOf.
  // Ajv's strictTypes is a non-standard lint; strict unknown-keyword handling stays on.
  const ajv = new Ajv2020({
    allErrors: true,
    ownProperties: true,
    strict: true,
    strictTypes: false,
    validateFormats: false,
  })
  addAnnotationKeywords(ajv)
  ajv.addKeyword({
    keyword: 'sudoZonePath',
    type: 'string',
    schemaType: 'object',
    errors: false,
    validate: (rules: Record<string, unknown>, value: string) => validateZonePathRules(rules, value),
  })
  const vocabulary = ZONE_PATH_META_SCHEMA.$vocabulary as Record<string, unknown>
  if (vocabulary['urn:sudo:nexus-vfs:vocab:zone-path:v1'] !== true) {
    throw new Error('ZonePath dialect does not require the sudoZonePath vocabulary')
  }
  ajv.addMetaSchema(ZONE_PATH_META_SCHEMA)
  ajv.addSchema(ZONE_ID_SCHEMA)
  ajv.addSchema(ZONE_PATH_SCHEMA)
  return ajv.compile(RESOURCE_SCHEMA)
}

let structuralValidator: ReturnType<typeof createStructuralValidator> | undefined

function getStructuralValidator(): ReturnType<typeof createStructuralValidator> {
  structuralValidator ??= createStructuralValidator()
  return structuralValidator
}

const escapePointer = (value: string | number) =>
  String(value).replaceAll('~', '~0').replaceAll('/', '~1')

function pointer(parts: readonly (string | number)[]): string {
  return parts.length === 0 ? '' : '/' + parts.map(escapePointer).join('/')
}

function propertyNameIssue(name: string, path: readonly (string | number)[]) {
  if (!SAFE_PROPERTY_PATTERN.test(name)) {
    return issue(
      'invalid_property_name',
      pointer(path),
      'propertyNames',
      'property name is not an allowed snake_case extension name',
    )
  }
  if (SECRET_PROPERTY_PATTERN.test(name)) {
    return issue(
      'secret_like_extension_key',
      pointer(path),
      'propertyNames',
      'secret-like property names are forbidden in ResourceRef extensions',
    )
  }
  return null
}

function inspectExtension(
  value: unknown,
  depth: number,
  path: readonly (string | number)[],
  budget: { nodes: number },
  ancestors: Set<object>,
): ResourceRefValidationIssue | null {
  budget.nodes += 1
  if (budget.nodes > MAX_RESOURCE_REF_JSON_BYTES) {
    return issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit')
  }
  if (value === null || typeof value === 'boolean') return null
  if (typeof value === 'string') {
    if (exceedsUnicodeScalarLength(value, MAX_EXTENSION_STRING_LENGTH)) {
      return issue(
        'extension_value_too_large',
        pointer(path),
        'maxLength',
        'ResourceRef extension value exceeds its structural limit',
      )
    }
    return isUnicodeScalarString(value)
      ? null
      : issue('invalid_utf8', pointer(path), 'encoding', 'JSON strings must contain Unicode scalar values')
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      return issue('non_finite_number', pointer(path), 'number', 'JSON numbers must be finite')
    }
    if (!Number.isInteger(value)) {
      return issue(
        'fractional_extension_number',
        pointer(path),
        'number',
        'ResourceRef extension numbers must represent safe integers',
      )
    }
    if (!Number.isSafeInteger(value)) {
      return issue(
        'unsafe_extension_integer',
        pointer(path),
        'number',
        'ResourceRef extension integers must use the JSON-safe range',
      )
    }
    return null
  }
  if (!value || typeof value !== 'object') {
    return issue('not_json_value', pointer(path), 'json', 'ResourceRef input must contain only JSON values')
  }
  if (ancestors.has(value)) {
    return issue('not_json_value', pointer(path), 'json', 'ResourceRef input must not contain cycles')
  }
  if (depth >= MAX_EXTENSION_DEPTH) {
    return issue(
      'extension_too_deep',
      pointer(path),
      'maxDepth',
      'ResourceRef extension nesting exceeds its limit',
    )
  }
  ancestors.add(value)
  if (Array.isArray(value)) {
    if (value.length > MAX_EXTENSION_ITEMS) {
      return issue(
        'extension_value_too_large',
        pointer(path),
        'maxItems',
        'ResourceRef extension value exceeds its structural limit',
      )
    }
    for (let index = 0; index < value.length; index += 1) {
      const child = inspectExtension(value[index], depth + 1, [...path, index], budget, ancestors)
      if (child) return child
    }
  } else {
    const prototype = Object.getPrototypeOf(value)
    if (prototype !== Object.prototype && prototype !== null) {
      return issue('not_json_value', pointer(path), 'json', 'ResourceRef input must contain plain JSON objects')
    }
    const entries = Object.entries(value)
    if (entries.length > MAX_EXTENSION_PROPERTIES) {
      return issue(
        'extension_value_too_large',
        pointer(path),
        'maxProperties',
        'ResourceRef extension value exceeds its structural limit',
      )
    }
    for (const [key, childValue] of entries) {
      const nameProblem = propertyNameIssue(key, path)
      if (nameProblem) return nameProblem
      const child = inspectExtension(childValue, depth + 1, [...path, key], budget, ancestors)
      if (child) return child
    }
  }
  ancestors.delete(value)
  return null
}

function addJsonBytes(used: { bytes: number }, count: number): boolean {
  used.bytes += count
  return used.bytes <= MAX_RESOURCE_REF_JSON_BYTES
}

function measureJsonBytes(
  value: unknown,
  used: { bytes: number },
  ancestors: Set<object>,
  depth = 0,
): 'too_large' | 'too_deep' | 'not_json' | null {
  if (value === null) return addJsonBytes(used, 4) ? null : 'too_large'
  if (typeof value === 'boolean') return addJsonBytes(used, value ? 4 : 5) ? null : 'too_large'
  if (typeof value === 'string') {
    if (value.length > MAX_RESOURCE_REF_JSON_BYTES - used.bytes) return 'too_large'
    return addJsonBytes(used, new TextEncoder().encode(JSON.stringify(value)).byteLength)
      ? null
      : 'too_large'
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value) || !Number.isSafeInteger(value)) return 'not_json'
    return addJsonBytes(used, String(value).length) ? null : 'too_large'
  }
  if (!value || typeof value !== 'object' || ancestors.has(value)) return 'not_json'
  if (depth > MAX_EXTENSION_DEPTH) return 'too_deep'
  ancestors.add(value)
  const isArray = Array.isArray(value)
  if (!addJsonBytes(used, 2)) return 'too_large'
  if (isArray) {
    for (let index = 0; index < value.length; index += 1) {
      if (index > 0 && !addJsonBytes(used, 1)) return 'too_large'
      const childResult = measureJsonBytes(value[index], used, ancestors, depth + 1)
      if (childResult) return childResult
    }
  } else {
    const entries = Object.entries(value)
    for (let index = 0; index < entries.length; index += 1) {
      if (index > 0 && !addJsonBytes(used, 1)) return 'too_large'
      const [key, child] = entries[index]
      if (!addJsonBytes(used, new TextEncoder().encode(JSON.stringify(key)).byteLength + 1)) {
        return 'too_large'
      }
      const childResult = measureJsonBytes(child, used, ancestors, depth + 1)
      if (childResult) return childResult
    }
  }
  ancestors.delete(value)
  return null
}

function encodedSizeIssue(value: unknown): ResourceRefValidationIssue | null {
  const result = measureJsonBytes(value, { bytes: 0 }, new Set())
  if (result === 'too_large') {
    return issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit')
  }
  if (result === 'too_deep') {
    return issue(
      'extension_too_deep',
      '',
      'maxDepth',
      'ResourceRef extension nesting exceeds its limit',
    )
  }
  return result === 'not_json'
    ? issue('not_json_value', '', 'json', 'ResourceRef input must contain only JSON values')
    : null
}

type SnapshotResult =
  | { value: JsonValue; issue: null }
  | { value: null; issue: ResourceRefValidationIssue }

function snapshotJsonValue(
  value: unknown,
  path: readonly (string | number)[] = [],
  ancestors = new Set<object>(),
  depth = 0,
  budget = { nodes: 0, bytes: 0 },
): SnapshotResult {
  budget.nodes += 1
  if (budget.nodes > MAX_RESOURCE_REF_JSON_BYTES) {
    return {
      value: null,
      issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
    }
  }
  if (value === null) {
    return addJsonBytes(budget, 4)
      ? { value: null, issue: null }
      : { value: null, issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit') }
  }
  if (typeof value === 'boolean') {
    return addJsonBytes(budget, value ? 4 : 5)
      ? { value, issue: null }
      : { value: null, issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit') }
  }
  if (typeof value === 'string') {
    if (value.length > MAX_RESOURCE_REF_JSON_BYTES - budget.bytes) {
      return { value: null, issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit') }
    }
    const bytes = new TextEncoder().encode(JSON.stringify(value)).byteLength
    return addJsonBytes(budget, bytes)
      ? { value, issue: null }
      : { value: null, issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit') }
  }
  if (typeof value === 'number') {
    return addJsonBytes(budget, String(value).length)
      ? { value, issue: null }
      : { value: null, issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit') }
  }
  if (!value || typeof value !== 'object') {
    return {
      value: null,
      issue: issue('not_json_value', pointer(path), 'json', 'ResourceRef input must contain only JSON values'),
    }
  }
  if (ancestors.has(value)) {
    return {
      value: null,
      issue: issue('not_json_value', pointer(path), 'json', 'ResourceRef input must not contain cycles'),
    }
  }
  if (depth > MAX_EXTENSION_DEPTH) {
    return {
      value: null,
      issue: issue(
        'extension_too_deep',
        pointer(path),
        'maxDepth',
        'ResourceRef extension nesting exceeds its limit',
      ),
    }
  }
  try {
    ancestors.add(value)
    if (!addJsonBytes(budget, 2)) {
      return {
        value: null,
        issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
      }
    }
    if (Array.isArray(value)) {
      if (value.length > MAX_EXTENSION_ITEMS) {
        return {
          value: null,
          issue: issue(
            'extension_value_too_large',
            pointer(path),
            'maxItems',
            'ResourceRef extension value exceeds its structural limit',
          ),
        }
      }
      const allowedKeys = new Set(['length', ...Array.from({ length: value.length }, (_, index) => String(index))])
      if (Reflect.ownKeys(value).some((key) => typeof key !== 'string' || !allowedKeys.has(key))) {
        return {
          value: null,
          issue: issue(
            'not_json_value',
            pointer(path),
            'json',
            'JSON arrays must not contain extra own properties',
          ),
        }
      }
      const snapshot: JsonValue[] = []
      for (let index = 0; index < value.length; index += 1) {
        if (index > 0 && !addJsonBytes(budget, 1)) {
          return {
            value: null,
            issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
          }
        }
        const descriptor = Object.getOwnPropertyDescriptor(value, String(index))
        if (!descriptor || !descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) {
          return {
            value: null,
            issue: issue(
              'not_json_value',
              pointer([...path, index]),
              'json',
              'JSON array entries must be enumerable data properties',
            ),
          }
        }
        const child = snapshotJsonValue(
          descriptor.value,
          [...path, index],
          ancestors,
          depth + 1,
          budget,
        )
        if (child.issue) return child
        snapshot.push(child.value)
      }
      ancestors.delete(value)
      return { value: snapshot, issue: null }
    }

    const prototype = Object.getPrototypeOf(value)
    if (prototype !== Object.prototype && prototype !== null) {
      return {
        value: null,
        issue: issue('not_json_value', pointer(path), 'json', 'ResourceRef input must contain plain JSON objects'),
      }
    }
    const entries: Array<[string, JsonValue]> = []
    const ownKeys = Reflect.ownKeys(value)
    if (ownKeys.length > MAX_EXTENSION_PROPERTIES) {
      return {
        value: null,
        issue: issue(
          'extension_value_too_large',
          pointer(path),
          'maxProperties',
          'ResourceRef extension value exceeds its structural limit',
        ),
      }
    }
    for (let keyIndex = 0; keyIndex < ownKeys.length; keyIndex += 1) {
      const key = ownKeys[keyIndex]
      if (keyIndex > 0 && !addJsonBytes(budget, 1)) {
        return {
          value: null,
          issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
        }
      }
      if (typeof key !== 'string') {
        return {
          value: null,
          issue: issue('not_json_value', pointer(path), 'json', 'JSON object keys must be strings'),
        }
      }
      if (
        key.length > MAX_RESOURCE_REF_JSON_BYTES - budget.bytes ||
        !addJsonBytes(budget, new TextEncoder().encode(JSON.stringify(key)).byteLength + 1)
      ) {
        return {
          value: null,
          issue: issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
        }
      }
      const descriptor = Object.getOwnPropertyDescriptor(value, key)
      if (!descriptor || !descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) {
        return {
          value: null,
          issue: issue(
            'not_json_value',
            pointer([...path, key]),
            'json',
            'JSON object members must be enumerable data properties',
          ),
        }
      }
      const child = snapshotJsonValue(
        descriptor.value,
        [...path, key],
        ancestors,
        depth + 1,
        budget,
      )
      if (child.issue) return child
      entries.push([key, child.value])
    }
    ancestors.delete(value)
    return { value: Object.fromEntries(entries), issue: null }
  } catch {
    return {
      value: null,
      issue: issue('not_json_value', pointer(path), 'json', 'ResourceRef input is not a stable JSON value'),
    }
  }
}

function preflight(value: unknown): ResourceRefValidationIssue | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null
  const prototype = Object.getPrototypeOf(value)
  if (prototype !== Object.prototype && prototype !== null) {
    return issue('not_json_value', '', 'json', 'ResourceRef input must be a plain JSON object')
  }
  const record = value as Record<string, unknown>
  const ownKeys = Reflect.ownKeys(record)
  if (ownKeys.some((key) => typeof key !== 'string' || !Object.prototype.propertyIsEnumerable.call(record, key))) {
    return issue('not_json_value', '', 'json', 'ResourceRef properties must be own enumerable string keys')
  }
  for (const required of RESOURCE_SCHEMA.required as string[]) {
    if (!Object.prototype.propertyIsEnumerable.call(record, required)) {
      return issue('missing_required', '', 'required', 'a required ResourceRef property is absent')
    }
  }
  if (ownKeys.length > Number(RESOURCE_SCHEMA.maxProperties)) {
    return issue('too_many_properties', '', 'maxProperties', 'ResourceRef contains too many properties')
  }
  const budget = { nodes: 0 }
  for (const [key, child] of Object.entries(record)) {
    if (KNOWN_FIELDS.has(key)) {
      if (typeof child !== 'string') {
        return issue('wrong_type', pointer([key]), 'type', 'property has the wrong JSON type')
      }
      continue
    }
    const nameProblem = propertyNameIssue(key, [])
    if (nameProblem) return nameProblem
    const childProblem = inspectExtension(child, 0, [key], budget, new Set([record]))
    if (childProblem) return childProblem
  }
  return encodedSizeIssue(value)
}

function categoryForAjvError(error: Record<string, unknown>): string {
  const path = String(error.instancePath ?? '')
  const keyword = String(error.keyword ?? '')
  if (keyword === 'required') return 'missing_required'
  if (keyword === 'const' && path === '/api_version') return 'unsupported_api_version'
  if (keyword === 'const' && path === '/kind') return 'unsupported_kind'
  if (keyword === 'type') return 'wrong_type'
  if (path === '/zone_id') return 'invalid_zone_id'
  if (path === '/path') return 'invalid_zone_path'
  if (path === '/version') return 'invalid_version'
  if (path === '/digest') return 'invalid_digest'
  if (path === '/media_type') return 'invalid_media_type'
  if (path === '/size_bytes') return 'invalid_size_bytes'
  if (keyword === 'propertyNames') return 'invalid_property_name'
  if (['maxLength', 'maxItems', 'maxProperties'].includes(keyword)) {
    return 'extension_value_too_large'
  }
  return 'schema_violation'
}

function validateResourceRefSnapshot(value: JsonValue): ResourceRefValidationIssue[] {
  const early = preflight(value)
  if (early) return [early]
  const validator = getStructuralValidator()
  if (validator(value)) return []
  const seen = new Set<string>()
  const issues: ResourceRefValidationIssue[] = []
  for (const error of validator.errors ?? []) {
    const category = categoryForAjvError(error as unknown as Record<string, unknown>)
    const path = String(error.instancePath ?? '')
    const keyword = String(error.keyword ?? 'schema')
    const key = JSON.stringify([category, path, keyword])
    if (seen.has(key)) continue
    seen.add(key)
    issues.push(issue(category, path, keyword, 'value does not satisfy the ResourceRef contract'))
  }
  return issues.sort((left, right) =>
    left.path.localeCompare(right.path) || left.category.localeCompare(right.category),
  )
}

export function validateResourceRef(value: unknown): ResourceRefValidationIssue[] {
  const snapshot = snapshotJsonValue(value)
  return snapshot.issue ? [snapshot.issue] : validateResourceRefSnapshot(snapshot.value)
}

function decodeInput(input: string | Uint8Array): string {
  if (typeof input === 'string') {
    if (input.length > MAX_RESOURCE_REF_JSON_BYTES) {
      throw new ResourceRefValidationError([
        issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
      ])
    }
    const bytes = new TextEncoder().encode(input)
    if (bytes.byteLength > MAX_RESOURCE_REF_JSON_BYTES) {
      throw new ResourceRefValidationError([
        issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
      ])
    }
    return input
  }
  if (input.byteLength > MAX_RESOURCE_REF_JSON_BYTES) {
    throw new ResourceRefValidationError([
      issue('document_too_large', '', 'maxBytes', 'ResourceRef JSON exceeds the document-size limit'),
    ])
  }
  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(input)
  } catch {
    throw new ResourceRefValidationError([
      issue('invalid_utf8', '', 'encoding', 'ResourceRef JSON must be UTF-8'),
    ])
  }
}

function nestingIssue(source: string): ResourceRefValidationIssue | null {
  const maxDepth = MAX_EXTENSION_DEPTH + 1
  const stack: string[] = []
  let inString = false
  let escaped = false
  for (let index = 0; index < source.length; index += 1) {
    const character = source[index]
    if (inString) {
      if (escaped) {
        if (character === 'u') {
          const hex = source.slice(index + 1, index + 5)
          if (!/^[0-9a-fA-F]{4}$/.test(hex)) {
            return issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
          }
          index += 4
        } else if (!'"\\/bfnrt'.includes(character)) {
          return issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
        }
        escaped = false
      } else if (character === '\\') {
        escaped = true
      } else if (character === '"') {
        inString = false
      } else if (character.charCodeAt(0) < 0x20) {
        return issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
      }
      continue
    }
    if (character === '"') {
      inString = true
    } else if (character === '/') {
      return issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
    } else if (character === '{' || character === '[') {
      stack.push(character)
      if (stack.length > maxDepth) {
        return issue(
          'extension_too_deep',
          '',
          'maxDepth',
          'ResourceRef extension nesting exceeds its limit',
        )
      }
    } else if (character === '}' || character === ']') {
      const expected = character === '}' ? '{' : '['
      if (stack.pop() !== expected) {
        return issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
      }
    }
  }
  return inString || escaped || stack.length > 0
    ? issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON')
    : null
}

function classifyJsonNumber(token: string): 'fractional_extension_number' | 'unsafe_extension_integer' | null {
  const match = token.match(/^-?(0|[1-9][0-9]*)(?:\.([0-9]+))?(?:[eE]([+-]?[0-9]+))?$/)
  if (!match) return 'unsafe_extension_integer'
  const negative = token.startsWith('-')
  const integerPart = match[1]
  const fraction = match[2] ?? ''
  const exponentText = match[3] ?? '0'
  const exponentNegative = exponentText.startsWith('-')
  const exponentDigits = exponentText.replace(/^[+-]?0*/, '') || '0'
  let digits = (integerPart + fraction).replace(/^0+/, '') || '0'
  if (digits === '0') return null
  if (exponentDigits.length > 6) {
    return exponentNegative ? 'fractional_extension_number' : 'unsafe_extension_integer'
  }
  const exponent = Number((exponentNegative ? '-' : '') + exponentDigits)
  const scale = fraction.length - exponent
  if (scale > 0) {
    if (scale > digits.length || !digits.endsWith('0'.repeat(scale))) {
      return 'fractional_extension_number'
    }
    digits = digits.slice(0, -scale) || '0'
  } else if (scale < 0) {
    const zeros = -scale
    if (digits.length + zeros > 16) return 'unsafe_extension_integer'
    digits += '0'.repeat(zeros)
  }
  if (digits.length > 16) return 'unsafe_extension_integer'
  const value = BigInt((negative ? '-' : '') + digits)
  return value < BigInt(MIN_SAFE_JSON_INTEGER) || value > BigInt(MAX_SAFE_JSON_INTEGER)
    ? 'unsafe_extension_integer'
    : null
}

function inspectSyntaxNode(
  node: NonNullable<ReturnType<typeof parseTree>>,
  source: string,
): ResourceRefValidationIssue | null {
  if (node.type === 'object') {
    const keys = new Set<string>()
    for (const property of node.children ?? []) {
      const keyNode = property.children?.[0]
      const valueNode = property.children?.[1]
      const key = keyNode?.value
      if (typeof key !== 'string' || !valueNode) continue
      if (keys.has(key)) {
        return issue('duplicate_property', '', 'uniqueKeys', 'ResourceRef JSON contains a duplicate property')
      }
      keys.add(key)
      const childIssue = inspectSyntaxNode(valueNode, source)
      if (childIssue) return childIssue
    }
  } else if (node.type === 'array') {
    for (const child of node.children ?? []) {
      const childIssue = inspectSyntaxNode(child, source)
      if (childIssue) return childIssue
    }
  } else if (node.type === 'number') {
    const token = source.slice(node.offset, node.offset + node.length)
    const category = classifyJsonNumber(token)
    if (category) {
      return issue(
        category,
        '',
        'number',
        category === 'fractional_extension_number'
          ? 'ResourceRef extension numbers must represent safe integers'
          : 'ResourceRef extension integers must use the JSON-safe range',
      )
    }
  }
  return null
}

function normalizeJson(value: unknown): JsonValue {
  if (Array.isArray(value)) return value.map(normalizeJson)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, child]) => [key, normalizeJson(child)]),
    )
  }
  return value as JsonValue
}

function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object') {
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child)
    Object.freeze(value)
  }
  return value
}

function sortJson(value: JsonValue): JsonValue {
  if (Array.isArray(value)) return value.map(sortJson)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortJson((value as Record<string, JsonValue>)[key])]),
    )
  }
  return value
}

export function parseResourceRefJson(input: string | Uint8Array): Readonly<ResourceRef> {
  const source = decodeInput(input)
  const depthIssue = nestingIssue(source)
  if (depthIssue) throw new ResourceRefValidationError([depthIssue])
  const syntaxErrors: Array<{ error: number; offset: number; length: number }> = []
  const root = parseTree(source, syntaxErrors, {
    allowTrailingComma: false,
    disallowComments: true,
    allowEmptyContent: false,
  })
  if (!root || syntaxErrors.length > 0) {
    throw new ResourceRefValidationError([
      issue('invalid_json', '', 'parse', 'ResourceRef payload is not valid JSON'),
    ])
  }
  const syntaxIssue = inspectSyntaxNode(root, source)
  if (syntaxIssue) throw new ResourceRefValidationError([syntaxIssue])
  const value = normalizeJson(getNodeValue(root))
  const issues = validateResourceRef(value)
  if (issues.length > 0) throw new ResourceRefValidationError(issues)
  return deepFreeze(value as ResourceRef)
}

export function assertResourceRef(value: unknown): asserts value is ResourceRef {
  const issues = validateResourceRef(value)
  if (issues.length > 0) throw new ResourceRefValidationError(issues)
}

export function isResourceRef(value: unknown): value is ResourceRef {
  return validateResourceRef(value).length === 0
}

export function serializeResourceRef(value: ResourceRef): string {
  const snapshot = snapshotJsonValue(value)
  if (snapshot.issue) throw new ResourceRefValidationError([snapshot.issue])
  const issues = validateResourceRefSnapshot(snapshot.value)
  if (issues.length > 0) throw new ResourceRefValidationError(issues)
  return JSON.stringify(sortJson(snapshot.value))
}

export function getResourceRefSchema(): Record<string, unknown> {
  return structuredClone(RESOURCE_SCHEMA)
}
