// @generated by contracts/generate.mjs — do not edit. Run `node contracts/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs 763f8c0fe (projections), nexus b19a9868c (schemas/fixtures).
// Validators are ajv 8.18.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

export { validateZone, validateZoneCreateRequest, validateZonePatchRequest, validateZoneGrant, validateZoneGrantCreateRequest, validateZoneOperation } from '../../validators.gen.js'
export { KNOWN_ERROR_CODES, CAPABILITY_PATTERN } from '../../codes.gen.js'
