// @generated by contracts/generate.mjs — do not edit. Run `node contracts/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs 763f8c0fe (projections), nexus b19a9868c (schemas/fixtures).
// Validators are ajv 8.18.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

import type { PrincipalRef } from '../../common/v1/index.gen.js'

export interface Zone {
  api_version: "auth.sudo.dev/v1"
  kind: "Zone"
  zone_id: string
  display_name: string
  description?: string
  status: "active" | "suspended" | "deleting" | "deleted"
  deployment: Record<string, unknown>
  labels?: { [key: string]: string }
  revision: string
  created_by: PrincipalRef
  created_at: string
  updated_at: string
  deleted_at?: string
}

export interface ZoneCreateRequest {
  api_version: "auth.sudo.dev/v1"
  kind: "ZoneCreateRequest"
  zone_id: string
  display_name: string
  description?: string
  deployment?: Record<string, unknown>
  labels?: { [key: string]: string }
}

export interface ZonePatchRequest {
  api_version: "auth.sudo.dev/v1"
  kind: "ZonePatchRequest"
  display_name?: string
  description?: string
  labels?: { [key: string]: string }
  deployment?: Record<string, unknown>
}

export interface ZoneGrant {
  api_version: "auth.sudo.dev/v1"
  kind: "ZoneGrant"
  grant_id: string
  zone_id: string
  grantee: PrincipalRef
  capabilities: Array<string>
  resource_prefixes?: Array<string>
  source?: Record<string, unknown>
  issued_by: PrincipalRef
  reason: string
  policy_version: string
  revision: string
  status: "pending" | "active" | "revoked" | "expired"
  created_at: string
  not_before?: string
  expires_at?: string
  revoked_at?: string
  revoked_by?: PrincipalRef
  revoke_reason?: string
}

export interface ZoneGrantCreateRequest {
  api_version: "auth.sudo.dev/v1"
  kind: "ZoneGrantCreateRequest"
  grantee: PrincipalRef
  capabilities: Array<string>
  resource_prefixes?: Array<string>
  source?: Record<string, unknown>
  reason: string
  policy_version?: string
  not_before?: string
  expires_at?: string
}

export interface ZoneOperation {
  api_version: "auth.sudo.dev/v1"
  kind: "ZoneOperation"
  operation_id: string
  action: "create" | "patch" | "suspend" | "resume" | "grant" | "revoke" | "mount" | "unmount" | "transfer" | "deprovision"
  zone_id?: string
  grant_id?: string
  state: "queued" | "running" | "waiting_dependency" | "succeeded" | "failed"
  step: string
  retryable: boolean
  revision?: string
  result?: Record<string, unknown>
  error?: Record<string, unknown>
  created_at: string
  updated_at: string
  completed_at?: string
}

export declare function validateZone(data: unknown): data is Zone
export declare function validateZoneCreateRequest(data: unknown): data is ZoneCreateRequest
export declare function validateZonePatchRequest(data: unknown): data is ZonePatchRequest
export declare function validateZoneGrant(data: unknown): data is ZoneGrant
export declare function validateZoneGrantCreateRequest(data: unknown): data is ZoneGrantCreateRequest
export declare function validateZoneOperation(data: unknown): data is ZoneOperation

export declare const KNOWN_ERROR_CODES: readonly string[]
export declare const CAPABILITY_PATTERN: RegExp
