// @generated by contracts/generate.mjs — do not edit. Run `node contracts/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs bc89aa638 (projections), nexus d78448594 (schemas/fixtures).
// Validators are ajv 8.18.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

export { validateZone, validateZoneCreateRequest, validateZonePatchRequest, validateZoneGrant, validateZoneGrantCreateRequest, validateZoneOperation, validateZoneDelegationScopeRule, validateZoneDelegationIssueRequest, validateZoneDelegation } from '../../validators.gen.js'
export { KNOWN_ERROR_CODES, CAPABILITY_PATTERN } from '../../codes.gen.js'
