// @generated by contracts/generate.mjs from nexus-vfs 21789169d
// contracts/zone-id/spec.json — do not edit. Run `node contracts/generate.mjs` instead;
// CI fails on any hand edit.
//
// The rule belongs to nexus-vfs, which generates its own validator from this
// same spec at compile time. This file exists because TypeScript has no
// equivalent build hook — the two are derived from one source, not written twice.

/** Shortest permitted zone id. */
export const ZONE_ID_MIN_LEN = 3
/** Longest permitted zone id. */
export const ZONE_ID_MAX_LEN = 63
/** Every character a zone id may contain. */
export const ZONE_ID_CHARSET = "abcdefghijklmnopqrstuvwxyz0123456789-"
/** Character a zone id may not start with. */
export const ZONE_ID_NO_LEADING = "-"
/** Character a zone id may not end with. */
export const ZONE_ID_NO_TRAILING = "-"

/** Why a zone id was refused; `null` when it is acceptable. */
export type ZoneIdRefusal =
  | { kind: 'length'; got: number }
  | { kind: 'character'; got: string; at: number }
  | { kind: 'leading' }
  | { kind: 'trailing' }

/**
 * Checks a zone id against the format, returning the first violation.
 *
 * Reserved ids are NOT checked here. They are kernel-owned strings whose SSOT is
 * nexus-vfs's own constants, and a consumer that restated them would be carrying
 * a copy that goes stale on a rename. Reserved ids are refused by the daemon.
 */
export function validateZoneId(id: string): ZoneIdRefusal | null {
  const len = [...id].length
  if (len < ZONE_ID_MIN_LEN || len > ZONE_ID_MAX_LEN) return { kind: 'length', got: len }
  if (id.startsWith(ZONE_ID_NO_LEADING)) return { kind: 'leading' }
  if (id.endsWith(ZONE_ID_NO_TRAILING)) return { kind: 'trailing' }
  const chars = [...id]
  for (let at = 0; at < chars.length; at++) {
    if (!ZONE_ID_CHARSET.includes(chars[at])) return { kind: 'character', got: chars[at], at }
  }
  return null
}

/** Human-readable refusal, phrased so the reader knows what to change. */
export function describeRefusal(r: ZoneIdRefusal): string {
  switch (r.kind) {
    case 'length':
      return `zone id must be ${ZONE_ID_MIN_LEN}–${ZONE_ID_MAX_LEN} characters, got ${r.got}`
    case 'character':
      return `zone id contains ${JSON.stringify(r.got)} at position ${r.at}; permitted characters are ${ZONE_ID_CHARSET}`
    case 'leading':
      return `zone id must not start with ${JSON.stringify(ZONE_ID_NO_LEADING)}`
    case 'trailing':
      return `zone id must not end with ${JSON.stringify(ZONE_ID_NO_TRAILING)}`
  }
}
