// @generated by contracts/generate.mjs from nexus-vfs 24f6730ec90fab8a035b2f5400ed313bda343fbe
// contracts/zone-id/spec.json — do not edit. Run `node contracts/generate.mjs` instead.

export const ZONE_ID_MIN_LEN = 3
export const ZONE_ID_MAX_LEN = 63
export const ZONE_ID_CHARSET = "abcdefghijklmnopqrstuvwxyz0123456789-"
export const ZONE_ID_NO_LEADING = "-"
export const ZONE_ID_NO_TRAILING = "-"

export type ZoneIdRefusal =
  | { kind: 'length'; got: number }
  | { kind: 'character'; got: string; at: number }
  | { kind: 'leading' }
  | { kind: 'trailing' }

export function validateZoneId(id: string): ZoneIdRefusal | null {
  const len = [...id].length
  if (len < ZONE_ID_MIN_LEN || len > ZONE_ID_MAX_LEN) return { kind: 'length', got: len }
  if (id.startsWith(ZONE_ID_NO_LEADING)) return { kind: 'leading' }
  if (id.endsWith(ZONE_ID_NO_TRAILING)) return { kind: 'trailing' }
  const chars = [...id]
  for (let at = 0; at < chars.length; at++) {
    if (!ZONE_ID_CHARSET.includes(chars[at])) return { kind: 'character', got: chars[at], at }
  }
  return null
}

export function describeRefusal(r: ZoneIdRefusal): string {
  switch (r.kind) {
    case 'length':
      return `zone id must be ${ZONE_ID_MIN_LEN}–${ZONE_ID_MAX_LEN} characters, got ${r.got}`
    case 'character':
      return `zone id contains ${JSON.stringify(r.got)} at position ${r.at}; permitted characters are ${ZONE_ID_CHARSET}`
    case 'leading':
      return `zone id must not start with ${JSON.stringify(ZONE_ID_NO_LEADING)}`
    case 'trailing':
      return `zone id must not end with ${JSON.stringify(ZONE_ID_NO_TRAILING)}`
  }
}
