// @generated by contracts/generate.mjs — do not edit. Run `node contracts/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs bc89aa638 (projections), nexus d78448594 (schemas/fixtures).
// Validators are ajv 8.18.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

/** Open registry: unknown codes are legal wire values within the same major. */
export const KNOWN_ERROR_CODES = /** @type {readonly string[]} */ (["INVALID_ZONE_ID","RESERVED_ZONE_ID","ZONE_ALREADY_EXISTS","ZONE_NOT_FOUND","ZONE_IMMUTABLE_FIELD","ZONE_REVISION_CONFLICT","ZONE_NOT_ACTIVE","ZONE_IN_USE","ZONE_DELETE_BLOCKED","ZONE_RUNTIME_UNAVAILABLE","ZONE_QUORUM_UNAVAILABLE","GRANT_NOT_FOUND","GRANT_NOT_ACTIVE","GRANT_REVOKED","GRANT_EXPIRED","MEMBERSHIP_UNAVAILABLE","AMBIGUOUS_GRANT","SCOPE_REQUIRED","RESOURCE_RELATION_DENIED","IDEMPOTENCY_CONFLICT","UNSUPPORTED_CONTRACT_MAJOR","UNSUPPORTED_CAPABILITY","PROJECTION_PENDING","PROJECTION_FAILED"])
export const CAPABILITY_PATTERN = /^zone\.[a-z-]+\.[a-z-]+$/
