// @generated by contracts/generate.mjs — do not edit. Run `node contracts/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs 763f8c0fe (projections), nexus c98baa34d (schemas/fixtures).
// Validators are ajv 8.18.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

export interface PrincipalRef {
  subject_type: "organization" | "user" | "agent" | "service"
  subject_id: string
  trust_domain?: string
}

export interface ResourceRef {
  api_version: "common.sudo.dev/v1"
  kind: "ResourceRef"
  zone_id: string
  path: string
  version?: string
  digest?: string
  media_type?: string
  size_bytes?: string
}

export declare function validatePrincipalRef(data: unknown): data is PrincipalRef
export declare function validateResourceRef(data: unknown): data is ResourceRef
