#!/usr/bin/env node
/**
 * Derives the non-Rust artifacts from the upstream contract specs.
 *
 * sudostack assembles; it does not define. The spec lives with whoever owns the
 * concept, and this fetches it at the revision named in `pin.json` — a pin
 * rather than a copy, because a copy is a second truth and starts drifting the
 * day it is made.
 *
 * Rust needs nothing from here: `nexus-vfs` generates its validator from the
 * same spec at compile time into OUT_DIR, so nothing is committed there to go
 * stale. TypeScript has no equivalent hook, so its artifact is committed — and
 * held honest by CI running this script and failing on any diff.
 *
 *   node contracts/generate.mjs          derive, write, report
 *   node contracts/generate.mjs --check  derive and fail if anything differs
 *
 * The generated files carry `.gen.` in the name and say where they came from,
 * but that is a courtesy, not the enforcement. The enforcement is the CI diff.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// Node's built-in fetch is undici, and undici does NOT read HTTP_PROXY /
// HTTPS_PROXY the way curl and most other clients do. A machine that reaches the
// network only through a proxy therefore fails here with a bare `fetch failed`,
// which reads as "the pinned revision is unreachable" rather than "the request
// never left the host".
//
// Deliberately not solved by depending on undici's ProxyAgent: this repository
// has no node_modules and should not grow one to fetch a JSON file. Node ships
// the dispatcher support already — `--use-env-proxy` (Node >=22.14) turns it on
// — so the fix is a flag, and the error below says so rather than leaving the
// reader to discover it.
const PROXY = process.env.HTTPS_PROXY ?? process.env.HTTP_PROXY

const HERE = dirname(fileURLToPath(import.meta.url))
const CHECK = process.argv.includes('--check')

const pin = JSON.parse(readFileSync(join(HERE, 'zone-id/pin.json'), 'utf8'))
const { rev, specs } = pin['nexus-vfs']

async function fetchSpec(path) {
  const url = `https://raw.githubusercontent.com/nexi-lab/nexus-vfs/${rev}/${path}`
  let res
  try {
    res = await fetch(url)
  } catch (cause) {
    const hint =
      PROXY && !process.execArgv.some((a) => a.startsWith('--use-env-proxy'))
        ? `
  HTTPS_PROXY is set but Node's fetch ignores it by default.` +
          `
  Re-run as: node --use-env-proxy contracts/generate.mjs`
        : ''
    throw new Error(`cannot reach ${url}: ${cause.message}${hint}`)
  }
  if (!res.ok) {
    throw new Error(
      `cannot read ${path} at ${rev.slice(0, 9)} (HTTP ${res.status}).\n` +
        `  Pinned revisions are immutable, so this is a network or access problem,\n` +
        `  not a stale pin — retry rather than bumping the pin to work around it.`,
    )
  }
  return JSON.parse(await res.text())
}

/** Cases derived from the spec, so they cannot describe a rule the spec does not have. */
function vectors(spec) {
  const { min, max } = spec.length
  const ok = 'a'
  const bad = spec.charset.allowed.includes('_') ? '!' : '_'
  const lead = spec.edges.no_leading
  const trail = spec.edges.no_trailing
  return [
    { id: ok.repeat(min), valid: true, why: 'shortest permitted' },
    { id: ok.repeat(max), valid: true, why: 'longest permitted' },
    { id: 'cloud-user-1001', valid: true, why: 'canonical shape' },
    { id: '550e8400-e29b-41d4-a716-446655440000', valid: true, why: 'a bare UUID is usable as-is' },
    { id: ok.repeat(min - 1), valid: false, why: 'shorter than the minimum' },
    { id: ok.repeat(max + 1), valid: false, why: 'longer than the maximum' },
    { id: `${lead}leading`, valid: false, why: 'leading separator' },
    { id: `trailing${trail}`, valid: false, why: 'trailing separator' },
    { id: 'Has-Upper', valid: false, why: 'uppercase is excluded, not folded' },
    { id: `has${bad}char`, valid: false, why: 'character outside the set' },
    { id: 'org:550e8400-e29b-41d4-a716-446655440000', valid: false, why: 'a colon is not in the set' },
  ]
}

function renderTs(spec) {
  const { min, max } = spec.length
  return `// @generated by contracts/generate.mjs from nexus-vfs ${rev.slice(0, 9)}
// ${specs['zone-id']} — do not edit. Run \`node contracts/generate.mjs\` instead;
// CI fails on any hand edit.
//
// The rule belongs to nexus-vfs, which generates its own validator from this
// same spec at compile time. This file exists because TypeScript has no
// equivalent build hook — the two are derived from one source, not written twice.

/** Shortest permitted zone id. */
export const ZONE_ID_MIN_LEN = ${min}
/** Longest permitted zone id. */
export const ZONE_ID_MAX_LEN = ${max}
/** Every character a zone id may contain. */
export const ZONE_ID_CHARSET = ${JSON.stringify(spec.charset.allowed)}
/** Character a zone id may not start with. */
export const ZONE_ID_NO_LEADING = ${JSON.stringify(spec.edges.no_leading)}
/** Character a zone id may not end with. */
export const ZONE_ID_NO_TRAILING = ${JSON.stringify(spec.edges.no_trailing)}

/** Why a zone id was refused; \`null\` when it is acceptable. */
export type ZoneIdRefusal =
  | { kind: 'length'; got: number }
  | { kind: 'character'; got: string; at: number }
  | { kind: 'leading' }
  | { kind: 'trailing' }

/**
 * Checks a zone id against the format, returning the first violation.
 *
 * Reserved ids are NOT checked here. They are kernel-owned strings whose SSOT is
 * nexus-vfs's own constants, and a consumer that restated them would be carrying
 * a copy that goes stale on a rename. Reserved ids are refused by the daemon.
 */
export function validateZoneId(id: string): ZoneIdRefusal | null {
  const len = [...id].length
  if (len < ZONE_ID_MIN_LEN || len > ZONE_ID_MAX_LEN) return { kind: 'length', got: len }
  if (id.startsWith(ZONE_ID_NO_LEADING)) return { kind: 'leading' }
  if (id.endsWith(ZONE_ID_NO_TRAILING)) return { kind: 'trailing' }
  const chars = [...id]
  for (let at = 0; at < chars.length; at++) {
    if (!ZONE_ID_CHARSET.includes(chars[at])) return { kind: 'character', got: chars[at], at }
  }
  return null
}

/** Human-readable refusal, phrased so the reader knows what to change. */
export function describeRefusal(r: ZoneIdRefusal): string {
  switch (r.kind) {
    case 'length':
      return \`zone id must be \${ZONE_ID_MIN_LEN}–\${ZONE_ID_MAX_LEN} characters, got \${r.got}\`
    case 'character':
      return \`zone id contains ${'${JSON.stringify(r.got)}'} at position \${r.at}; permitted characters are \${ZONE_ID_CHARSET}\`
    case 'leading':
      return \`zone id must not start with ${'${JSON.stringify(ZONE_ID_NO_LEADING)}'}\`
    case 'trailing':
      return \`zone id must not end with ${'${JSON.stringify(ZONE_ID_NO_TRAILING)}'}\`
  }
}
`
}

function renderExamples(spec, vecs) {
  const rows = vecs
    .map((v) => {
      const shown = v.id.length > 44 ? `${v.id.slice(0, 41)}…` : v.id
      return `| \`${shown}\` | ${v.valid ? '✅' : '❌'} | ${v.why} |`
    })
    .join('\n')
  return `<!-- @generated by contracts/generate.mjs from nexus-vfs ${rev.slice(0, 9)} — do not edit. -->

# zone-id — what is and is not accepted

Derived from the spec, not written by hand, so these cannot describe a rule the
spec does not have. That is the point: examples written separately drift from
the rule they illustrate, and a wrong example is worse than none.

**The rule**: ${spec.length.min}–${spec.length.max} characters, from \`${spec.charset.allowed}\`,
not starting with \`${spec.edges.no_leading}\` or ending with \`${spec.edges.no_trailing}\`.
Reserved ids are refused by the daemon.

| id | | why |
|---|---|---|
${rows}

**It cannot be changed after creation.** ${spec.mutability.why}
`
}

const spec = await fetchSpec(specs['zone-id'])
const vecs = vectors(spec)

const outputs = [
  ['zone-id/zone-id.gen.ts', renderTs(spec)],
  ['zone-id/vectors.gen.json', `${JSON.stringify(vecs, null, 2)}\n`],
  ['zone-id/EXAMPLES.gen.md', renderExamples(spec, vecs)],
]

let stale = 0
for (const [rel, content] of outputs) {
  const path = join(HERE, rel)
  let existing = null
  try {
    existing = readFileSync(path, 'utf8')
  } catch {
    /* first run */
  }
  if (existing === content) continue
  stale++
  if (CHECK) {
    console.error(`stale: ${rel}`)
    continue
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`wrote  ${rel}`)
}

if (CHECK && stale > 0) {
  console.error(
    `\n${stale} derived file(s) do not match the spec at ${rev.slice(0, 9)}.\n` +
      `Run \`node contracts/generate.mjs\` and commit the result.`,
  )
  process.exit(1)
}
console.log(stale === 0 ? 'up to date' : `${stale} file(s) regenerated`)
