//! Derived zone-v1 product contract DTOs and validators (auth/common v1).
//!
//! Assembled by sudostack from the pinned owner revisions: nexus owns the
//! product schemas, nexus-vfs owns zone-id/zone-path — the validation rules
//! for both are generated by `build.rs` from the materialized owner specs, so
//! this crate never restates (and can never disagree with) an owner rule.
//! Rust consumers join the TS package in facing the same fixture corpus
//! (`crates/sudo-contracts/tests/conformance.rs`).
//!
//! Structure vs. value rules: serde owns the structural layer (required
//! fields, closed enums, unknown-optional tolerance — serde ignores unknown
//! fields, which is exactly the wire rule); each DTO's `validate()` owns the
//! value layer (api_version consts, zone-id/path projections, digest/decimal/
//! timestamp shapes). A payload is contract-valid only when both layers pass.

mod rules {
    include!(concat!(env!("OUT_DIR"), "/generated_rules.rs"));

    /// Format check against the generated charset/length/edge constants.
    pub fn validate_format(s: &str) -> bool {
        let chars: Vec<char> = s.chars().collect();
        if chars.len() < ZONE_ID_MIN_LEN || chars.len() > ZONE_ID_MAX_LEN {
            return false;
        }
        if chars.first() == Some(&ZONE_ID_NO_LEADING) || chars.last() == Some(&ZONE_ID_NO_TRAILING) {
            return false;
        }
        chars.iter().all(|c| ZONE_ID_CHARSET.contains(*c))
    }

    /// Path check against the generated zone-path constants: absolute, no
    /// empty/forbidden components, no reserved prefixes, depth/length bounds,
    /// allowed charset.
    pub fn validate_path(s: &str) -> bool {
        if !s.starts_with('/') || s.len() > ZONE_PATH_MAX_LEN {
            return false;
        }
        if s == "/" {
            return true;
        }
        let components: Vec<&str> = s[1..].split('/').collect();
        if components.len() > ZONE_PATH_MAX_DEPTH {
            return false;
        }
        if ZONE_PATH_RESERVED_PREFIXES.contains(&components[0]) {
            return false;
        }
        components.iter().all(|c| {
            !c.is_empty()
                && c.len() <= 255
                && !ZONE_PATH_FORBIDDEN_COMPONENTS.contains(c)
                && c.chars().all(|ch| ZONE_PATH_COMPONENT_ALLOWED.contains(ch))
        })
    }
}

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub const API_VERSION_AUTH_V1: &str = "auth.sudo.dev/v1";
pub const API_VERSION_COMMON_V1: &str = "common.sudo.dev/v1";

/// Open registry (§4.6): known constants for callers that want them; unknown
/// codes are legal wire values within the same major.
pub const KNOWN_CAPABILITIES: &[&str] = &[
    "zone.data.read",
    "zone.data.write",
    "zone.runtime.execute",
    "zone.metadata.manage",
    "zone.grants.manage",
    "zone.data.export",
    "zone.lifecycle.delete",
];

/// Fixed known error codes (§4.10). The registry is open: clients judge by
/// code/retryable only, never by message.
pub const KNOWN_ERROR_CODES: &[&str] = &[
    "INVALID_ZONE_ID",
    "RESERVED_ZONE_ID",
    "ZONE_ALREADY_EXISTS",
    "ZONE_NOT_FOUND",
    "ZONE_IMMUTABLE_FIELD",
    "ZONE_REVISION_CONFLICT",
    "ZONE_NOT_ACTIVE",
    "ZONE_IN_USE",
    "ZONE_DELETE_BLOCKED",
    "ZONE_RUNTIME_UNAVAILABLE",
    "ZONE_QUORUM_UNAVAILABLE",
    "GRANT_NOT_FOUND",
    "GRANT_NOT_ACTIVE",
    "GRANT_REVOKED",
    "GRANT_EXPIRED",
    "RESOURCE_RELATION_DENIED",
    "IDEMPOTENCY_CONFLICT",
    "UNSUPPORTED_CONTRACT_MAJOR",
    "UNSUPPORTED_CAPABILITY",
    "PROJECTION_PENDING",
    "PROJECTION_FAILED",
];

// ── zone-id / zone-path: generated rules, hand-written checkers ─────────────

/// Tenant-create admission (§4.2): every format rule plus reserved rejection.
pub fn validate_tenant_zone_id_create(s: &str) -> bool {
    rules::validate_format(s) && !rules::RESERVED_TENANT.contains(&s)
}

/// Existing/historical identity reference (§4.2): format, or a reserved id.
pub fn validate_existing_zone_id_ref(s: &str) -> bool {
    rules::validate_format(s) || rules::RESERVED_EXISTING.contains(&s)
}

/// Zone-relative absolute path per the materialized zone-path spec.
pub fn validate_zone_path(s: &str) -> bool {
    rules::validate_path(s)
}

// ── value-shape helpers ──────────────────────────────────────────────────────

pub fn is_rfc3339(s: &str) -> bool {
    let b = s.as_bytes();
    let digit = |i: usize| b.get(i).is_some_and(u8::is_ascii_digit);
    // YYYY-MM-DDTHH:MM:SS
    if b.len() < 19
        || !(digit(0) && digit(1) && digit(2) && digit(3)
            && b[4] == b'-' && digit(5) && digit(6) && b[7] == b'-'
            && digit(8) && digit(9) && b[10] == b'T'
            && digit(11) && digit(12) && b[13] == b':'
            && digit(14) && digit(15) && b[16] == b':'
            && digit(17) && digit(18))
    {
        return false;
    }
    // Optional fraction, then Z or ±HH:MM.
    let rest = &s[19..];
    let rest = if let Some(stripped) = rest.strip_prefix('.') {
        let frac_len = stripped.chars().take_while(|c| c.is_ascii_digit()).count();
        if frac_len == 0 {
            return false;
        }
        &stripped[frac_len..]
    } else {
        rest
    };
    if rest == "Z" {
        return true;
    }
    let rb = rest.as_bytes();
    rb.len() == 6
        && (rb[0] == b'+' || rb[0] == b'-')
        && rb[1].is_ascii_digit() && rb[2].is_ascii_digit()
        && rb[3] == b':'
        && rb[4].is_ascii_digit() && rb[5].is_ascii_digit()
}

pub fn is_digest(s: &str) -> bool {
    match s.split_once(':') {
        Some((algo, value)) => {
            !algo.is_empty()
                && algo.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
                && !value.is_empty()
                && value.bytes().all(|b| b.is_ascii_alphanumeric() || matches!(b, b'+' | b'/' | b'=' | b'.' | b'_' | b'-'))
        }
        None => false,
    }
}

pub fn is_decimal_string(s: &str) -> bool {
    !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit())
}

pub fn is_capability(s: &str) -> bool {
    let mut parts = s.split('.');
    let Some(first) = parts.next() else { return false };
    let Some(second) = parts.next() else { return false };
    let Some(third) = parts.next() else { return false };
    if parts.next().is_some() {
        return false;
    }
    let seg = |x: &str| !x.is_empty() && x.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-');
    first == "zone" && seg(second) && seg(third)
}

/// Validation error: machine-judgeable, no message parsing required.
#[derive(Debug)]
pub struct ContractViolation {
    pub field: &'static str,
}

pub trait Validate {
    fn validate(&self) -> Result<(), ContractViolation>;
}

// ── common/v1 ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SubjectType {
    Organization,
    User,
    Agent,
    Service,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PrincipalRef {
    pub subject_type: SubjectType,
    pub subject_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trust_domain: Option<String>,
}

impl Validate for PrincipalRef {
    fn validate(&self) -> Result<(), ContractViolation> {
        (!self.subject_id.is_empty())
            .then_some(())
            .ok_or(ContractViolation { field: "subject_id" })?;
        if let Some(td) = &self.trust_domain {
            (!td.is_empty()).then_some(()).ok_or(ContractViolation { field: "trust_domain" })?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ResourceRef {
    pub api_version: String,
    pub kind: String,
    pub zone_id: String,
    pub path: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<String>,
}

impl Validate for ResourceRef {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_COMMON_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ResourceRef").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        validate_existing_zone_id_ref(&self.zone_id).then_some(()).ok_or(ContractViolation { field: "zone_id" })?;
        validate_zone_path(&self.path).then_some(()).ok_or(ContractViolation { field: "path" })?;
        if let Some(v) = &self.version {
            (!v.is_empty()).then_some(()).ok_or(ContractViolation { field: "version" })?;
        }
        if let Some(d) = &self.digest {
            is_digest(d).then_some(()).ok_or(ContractViolation { field: "digest" })?;
        }
        if let Some(s) = &self.size_bytes {
            is_decimal_string(s).then_some(()).ok_or(ContractViolation { field: "size_bytes" })?;
        }
        Ok(())
    }
}

// ── auth/v1 ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ZoneStatus {
    Active,
    Suspended,
    Deleting,
    Deleted,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Location {
    Cloud,
    Private,
    Edge,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum DataDomain {
    Office,
    Core,
    General,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneDeployment {
    pub location: Location,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_domain: Option<DataDomain>,
    pub trust_domain: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replication_policy_ref: Option<ResourceRef>,
}

impl Validate for ZoneDeployment {
    fn validate(&self) -> Result<(), ContractViolation> {
        (!self.trust_domain.is_empty()).then_some(()).ok_or(ContractViolation { field: "trust_domain" })?;
        if let Some(r) = &self.region {
            (!r.is_empty()).then_some(()).ok_or(ContractViolation { field: "region" })?;
        }
        if let Some(r) = &self.replication_policy_ref {
            r.validate()?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Zone {
    pub api_version: String,
    pub kind: String,
    pub zone_id: String,
    pub display_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ZoneStatus,
    pub deployment: ZoneDeployment,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<HashMap<String, String>>,
    pub revision: String,
    pub created_by: PrincipalRef,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
}

impl Validate for Zone {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "Zone").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        validate_existing_zone_id_ref(&self.zone_id).then_some(()).ok_or(ContractViolation { field: "zone_id" })?;
        (!self.display_name.is_empty()).then_some(()).ok_or(ContractViolation { field: "display_name" })?;
        (!self.revision.is_empty()).then_some(()).ok_or(ContractViolation { field: "revision" })?;
        is_rfc3339(&self.created_at).then_some(()).ok_or(ContractViolation { field: "created_at" })?;
        is_rfc3339(&self.updated_at).then_some(()).ok_or(ContractViolation { field: "updated_at" })?;
        if let Some(d) = &self.deleted_at {
            is_rfc3339(d).then_some(()).ok_or(ContractViolation { field: "deleted_at" })?;
        }
        self.created_by.validate()?;
        self.deployment.validate()?;
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneCreateRequest {
    pub api_version: String,
    pub kind: String,
    pub zone_id: String,
    pub display_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment: Option<ZoneDeployment>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<HashMap<String, String>>,
}

impl Validate for ZoneCreateRequest {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ZoneCreateRequest").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        // Create admission uses the STRICT tenant projection: reserved ids are
        // rejected here even though the record validator would accept them.
        validate_tenant_zone_id_create(&self.zone_id).then_some(()).ok_or(ContractViolation { field: "zone_id" })?;
        (!self.display_name.is_empty()).then_some(()).ok_or(ContractViolation { field: "display_name" })?;
        if let Some(d) = &self.deployment {
            d.validate()?;
        }
        Ok(())
    }
}

/// Whitelist patch: unknown keys are a client bug, not forward compatibility.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ZonePatchPlacement {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_domain: Option<DataDomain>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ZonePatchRequest {
    pub api_version: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<HashMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment: Option<ZonePatchPlacement>,
}

impl Validate for ZonePatchRequest {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ZonePatchRequest").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        if let Some(n) = &self.display_name {
            (!n.is_empty()).then_some(()).ok_or(ContractViolation { field: "display_name" })?;
        }
        if let Some(d) = &self.deployment {
            if let Some(r) = &d.region {
                (!r.is_empty()).then_some(()).ok_or(ContractViolation { field: "region" })?;
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum GrantSourceType {
    Manual,
    MossOrgBinding,
    Migration,
    System,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneGrantSource {
    pub source_type: GrantSourceType,
    pub source_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum GrantStatus {
    Pending,
    Active,
    Revoked,
    Expired,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneGrant {
    pub api_version: String,
    pub kind: String,
    pub grant_id: String,
    pub zone_id: String,
    pub grantee: PrincipalRef,
    pub capabilities: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_prefixes: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<ZoneGrantSource>,
    pub issued_by: PrincipalRef,
    pub reason: String,
    pub policy_version: String,
    pub revision: String,
    pub status: GrantStatus,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub not_before: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<PrincipalRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoke_reason: Option<String>,
}

impl ZoneGrant {
    pub fn has_unknown_capabilities(&self) -> bool {
        self.capabilities.iter().any(|c| !KNOWN_CAPABILITIES.contains(&c.as_str()))
    }
}

impl Validate for ZoneGrant {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ZoneGrant").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        (!self.grant_id.is_empty()).then_some(()).ok_or(ContractViolation { field: "grant_id" })?;
        validate_existing_zone_id_ref(&self.zone_id).then_some(()).ok_or(ContractViolation { field: "zone_id" })?;
        self.capabilities.iter().all(|c| is_capability(c)).then_some(()).ok_or(ContractViolation { field: "capabilities" })?;
        if let Some(prefixes) = &self.resource_prefixes {
            prefixes.iter().all(|p| validate_zone_path(p)).then_some(()).ok_or(ContractViolation { field: "resource_prefixes" })?;
        }
        (!self.reason.is_empty()).then_some(()).ok_or(ContractViolation { field: "reason" })?;
        (!self.policy_version.is_empty()).then_some(()).ok_or(ContractViolation { field: "policy_version" })?;
        (!self.revision.is_empty()).then_some(()).ok_or(ContractViolation { field: "revision" })?;
        is_rfc3339(&self.created_at).then_some(()).ok_or(ContractViolation { field: "created_at" })?;
        self.grantee.validate()?;
        self.issued_by.validate()?;
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneGrantCreateRequest {
    pub api_version: String,
    pub kind: String,
    pub grantee: PrincipalRef,
    pub capabilities: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_prefixes: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<ZoneGrantSource>,
    pub reason: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub not_before: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl Validate for ZoneGrantCreateRequest {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ZoneGrantCreateRequest").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        self.capabilities.iter().all(|c| is_capability(c)).then_some(()).ok_or(ContractViolation { field: "capabilities" })?;
        if let Some(prefixes) = &self.resource_prefixes {
            prefixes.iter().all(|p| validate_zone_path(p)).then_some(()).ok_or(ContractViolation { field: "resource_prefixes" })?;
        }
        (!self.reason.is_empty()).then_some(()).ok_or(ContractViolation { field: "reason" })?;
        self.grantee.validate()?;
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ZoneAction {
    Create,
    Patch,
    Suspend,
    Resume,
    Grant,
    Revoke,
    Mount,
    Unmount,
    Transfer,
    Deprovision,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum OperationState {
    Queued,
    Running,
    WaitingDependency,
    Succeeded,
    Failed,
}

/// Inline ErrorInfo (§4.10). Clients judge by code/retryable, never message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ErrorInfo {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cause_ref: Option<ResourceRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl ErrorInfo {
    pub fn is_unknown_code(&self) -> bool {
        !KNOWN_ERROR_CODES.contains(&self.code.as_str())
    }
}

impl Validate for ErrorInfo {
    fn validate(&self) -> Result<(), ContractViolation> {
        let wellformed = self
            .code
            .bytes()
            .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_')
            && self.code.starts_with(|c: char| c.is_ascii_uppercase())
            && !self.code.is_empty();
        wellformed.then_some(()).ok_or(ContractViolation { field: "code" })?;
        if let Some(r) = &self.cause_ref {
            r.validate()?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneOperation {
    pub api_version: String,
    pub kind: String,
    pub operation_id: String,
    pub action: ZoneAction,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zone_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grant_id: Option<String>,
    pub state: OperationState,
    pub step: String,
    pub retryable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorInfo>,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
}

impl Validate for ZoneOperation {
    fn validate(&self) -> Result<(), ContractViolation> {
        (self.api_version == API_VERSION_AUTH_V1).then_some(()).ok_or(ContractViolation { field: "api_version" })?;
        (self.kind == "ZoneOperation").then_some(()).ok_or(ContractViolation { field: "kind" })?;
        (!self.operation_id.is_empty()).then_some(()).ok_or(ContractViolation { field: "operation_id" })?;
        if let Some(z) = &self.zone_id {
            validate_existing_zone_id_ref(z).then_some(()).ok_or(ContractViolation { field: "zone_id" })?;
        }
        (!self.step.is_empty()).then_some(()).ok_or(ContractViolation { field: "step" })?;
        is_rfc3339(&self.created_at).then_some(()).ok_or(ContractViolation { field: "created_at" })?;
        is_rfc3339(&self.updated_at).then_some(()).ok_or(ContractViolation { field: "updated_at" })?;
        if let Some(c) = &self.completed_at {
            is_rfc3339(c).then_some(()).ok_or(ContractViolation { field: "completed_at" })?;
        }
        if let Some(e) = &self.error {
            e.validate()?;
        }
        Ok(())
    }
}
