#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { schemaFiles, schemaExportName, readJson, stableJson } from './schema-lib.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')
const CHECK = process.argv.includes('--check')
const OUT = join(REPO, 'contracts/common/v1/common.gen.ts')

const schemas = Object.fromEntries(
  schemaFiles()
    .filter((path) => path.includes('/common/v1/'))
    .map((path) => [schemaExportName(path), readJson(path)]),
)

const content = `// @generated by tools/generate-common.mjs from schemas/common/v1/*.schema.json
// Do not edit. Run \`node tools/generate-common.mjs\` instead;
// CI fails on any hand edit.

export const COMMON_API_VERSION = 'common.sudo.dev/v1'

export type ContractEnvelope = {
  api_version: string
  kind: string
  [key: string]: unknown
}

export type ResourceRef = {
  api_version: typeof COMMON_API_VERSION
  kind: 'ResourceRef'
  zone_id: string
  path: string
  version?: string
  digest?: string
  media_type?: string
  size_bytes?: number
  [key: string]: unknown
}

export type ErrorInfo = {
  api_version: typeof COMMON_API_VERSION
  kind: 'ErrorInfo'
  code: string
  message: string
  retryable: boolean
  details?: Record<string, unknown>
  cause_ref?: ResourceRef
  [key: string]: unknown
}

export type CommonObject = ResourceRef | ErrorInfo

export type ValidationIssue = {
  path: string
  message: string
}

export type ParseResult<T> =
  | { ok: true; value: T }
  | { ok: false; issues: ValidationIssue[] }

export const COMMON_SCHEMAS = ${JSON.stringify(schemas, null, 2)} as const

const KIND_TO_SCHEMA: Record<string, unknown> = {
  ResourceRef: COMMON_SCHEMAS.ResourceRef,
  ErrorInfo: COMMON_SCHEMAS.ErrorInfo,
}

export function safeParseCommon(value: unknown): ParseResult<CommonObject> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, issues: [{ path: '$', message: 'expected object' }] }
  }
  const kind = (value as { kind?: unknown }).kind
  const schema = typeof kind === 'string' ? KIND_TO_SCHEMA[kind] : undefined
  if (!schema) {
    return { ok: false, issues: [{ path: '$.kind', message: \`unsupported kind \${JSON.stringify(kind)}\` }] }
  }
  const issues = validateAgainstSchema(schema as Schema, value, '$')
  return issues.length ? { ok: false, issues } : { ok: true, value: value as CommonObject }
}

export function parseCommon(value: unknown): CommonObject {
  const result = safeParseCommon(value)
  if (result.ok) return result.value
  throw new Error(result.issues.map((issue) => \`\${issue.path}: \${issue.message}\`).join('; '))
}

export function safeParseResourceRef(value: unknown): ParseResult<ResourceRef> {
  const result = safeParseCommon(value)
  if (!result.ok) return result
  if (result.value.kind !== 'ResourceRef') {
    return { ok: false, issues: [{ path: '$.kind', message: 'expected ResourceRef' }] }
  }
  return { ok: true, value: result.value }
}

export function safeParseErrorInfo(value: unknown): ParseResult<ErrorInfo> {
  const result = safeParseCommon(value)
  if (!result.ok) return result
  if (result.value.kind !== 'ErrorInfo') {
    return { ok: false, issues: [{ path: '$.kind', message: 'expected ErrorInfo' }] }
  }
  return { ok: true, value: result.value }
}

type Schema = {
  $ref?: string
  type?: string
  const?: unknown
  enum?: unknown[]
  required?: string[]
  additionalProperties?: boolean
  properties?: Record<string, Schema>
  minLength?: number
  maxLength?: number
  pattern?: string
  minimum?: number
  maximum?: number
}

function validateAgainstSchema(schema: Schema, value: unknown, path: string): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  if (schema.$ref) {
    const ref = schema.$ref.split('/').pop()?.replace('.schema.json', '')
    const resolved = ref === 'resource-ref' ? COMMON_SCHEMAS.ResourceRef : undefined
    if (!resolved) return [{ path, message: \`unresolved ref \${schema.$ref}\` }]
    return validateAgainstSchema(resolved as Schema, value, path)
  }
  if ('const' in schema && value !== schema.const) {
    return [{ path, message: \`expected const \${JSON.stringify(schema.const)}\` }]
  }
  if (schema.type && !typeMatches(schema.type, value)) {
    return [{ path, message: \`expected \${schema.type}\` }]
  }
  if ((schema.type === 'object' || schema.properties || schema.required) && value && typeof value === 'object' && !Array.isArray(value)) {
    const obj = value as Record<string, unknown>
    for (const key of Object.keys(obj)) {
      if (isForbiddenInlineField(key)) {
        issues.push({ path: \`\${path}.\${key}\`, message: 'forbidden inline secret-like field' })
      }
    }
    for (const required of schema.required ?? []) {
      if (!(required in obj)) issues.push({ path: \`\${path}.\${required}\`, message: 'missing required property' })
    }
    const props = schema.properties ?? {}
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(obj)) {
        if (!(key in props)) issues.push({ path: \`\${path}.\${key}\`, message: 'unexpected property' })
      }
    }
    for (const [key, child] of Object.entries(props)) {
      if (key in obj) issues.push(...validateAgainstSchema(child, obj[key], \`\${path}.\${key}\`))
    }
  }
  if (typeof value === 'string') {
    if (schema.minLength !== undefined && [...value].length < schema.minLength) issues.push({ path, message: \`string shorter than \${schema.minLength}\` })
    if (schema.maxLength !== undefined && [...value].length > schema.maxLength) issues.push({ path, message: \`string longer than \${schema.maxLength}\` })
    if (schema.pattern && !new RegExp(schema.pattern).test(value)) issues.push({ path, message: \`string does not match /\${schema.pattern}/\` })
  }
  if (typeof value === 'number') {
    if (schema.type === 'integer' && !Number.isInteger(value)) issues.push({ path, message: 'expected integer' })
    if (schema.minimum !== undefined && value < schema.minimum) issues.push({ path, message: \`number below \${schema.minimum}\` })
    if (schema.maximum !== undefined && value > schema.maximum) issues.push({ path, message: \`number above \${schema.maximum}\` })
  }
  return issues
}

function typeMatches(type: string, value: unknown): boolean {
  if (type === 'array') return Array.isArray(value)
  if (type === 'integer') return Number.isInteger(value)
  if (type === 'object') return !!value && typeof value === 'object' && !Array.isArray(value)
  return typeof value === type
}

function isForbiddenInlineField(key: string): boolean {
  return /secret|credential|password|private[_-]?key|access[_-]?token|refresh[_-]?token|id[_-]?token|api[_-]?key/i.test(key)
}
`

let existing = null
try {
  existing = readFileSync(OUT, 'utf8')
} catch {}

if (existing !== content) {
  if (CHECK) {
    console.error('stale: contracts/common/v1/common.gen.ts')
    process.exit(1)
  }
  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, content)
  console.log('wrote  contracts/common/v1/common.gen.ts')
} else {
  console.log('common generated artifact up to date')
}
