// @generated by contracts/zone-v1/generate.mjs — do not edit. Run `node --use-env-proxy contracts/zone-v1/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs bc89aa638 (projections), nexus d78448594 (schemas/fixtures).
// Validators are ajv 8.20.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

import type { ZoneDelegationScopeRule } from '../../auth/v1/index.gen.js'

export interface RuntimeResourceScope {
  schema_version: 1
  zone_id: string
  rules: Array<ZoneDelegationScopeRule>
}

export declare function validateRuntimeResourceScope(data: unknown): data is RuntimeResourceScope
