// @generated by contracts/zone-v1/generate.mjs — do not edit. Run `node --use-env-proxy contracts/zone-v1/generate.mjs` instead; CI fails on any hand edit.
// Owners at pinned revisions: nexus-vfs bc89aa638 (projections), nexus 21534129d (schemas/fixtures).
// Validators are ajv 8.20.0 standalone output (2020-12): self-contained, consumers need no ajv at runtime.

export { validateRuntimeResourceScope } from '../../validators.gen.js'
